import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";
import { notFound } from "next/navigation";
import {
  setRequestLocale,
  getTranslations,
  getMessages,
} from "next-intl/server";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { Inter, IBM_Plex_Sans_Arabic } from "next/font/google";

import { routing, localeMetadata, type Locale } from "@/i18n/routing";
import { siteConfig } from "@/config/site";
import { getCanonicalUrl, getAlternateUrls, getAlternateLocales } from "@/config/seo";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { AnalyticsProvider } from "@/lib/analytics";

import "../globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
  preload: true,
  fallback: ['system-ui', 'arial'],
  adjustFontFallback: true,
});

const ibmPlexArabic = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-arabic",
  preload: true,
  fallback: ['system-ui', 'arial'],
  adjustFontFallback: true,
});

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "metadata" });
  const typedLocale = locale as Locale;

  return {
    metadataBase: new URL(siteConfig.url),
    title: {
      default: t("siteName"),
      template: `%s | ${t("siteName")}`,
    },
    description: t("siteDescription"),
    keywords: siteConfig.keywords,
    authors: [{ name: siteConfig.name, url: siteConfig.url }],
    creator: siteConfig.name,
    publisher: siteConfig.name,
    category: "Business Software",
    classification: "Software as a Service",
    applicationName: siteConfig.name,
    generator: "Next.js",
    referrer: "origin-when-cross-origin",
    verification: {
      google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
      // Add other verification IDs as needed
      // yandex: process.env.NEXT_PUBLIC_YANDEX_VERIFICATION,
      // other: { 'facebook-domain-verification': process.env.NEXT_PUBLIC_FB_DOMAIN_VERIFICATION },
    },
    robots: {
      index: true,
      follow: true,
      nocache: false,
      googleBot: {
        index: true,
        follow: true,
        noimageindex: false,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    alternates: {
      canonical: getCanonicalUrl("", typedLocale),
      languages: getAlternateUrls(""),
      types: {
        'application/rss+xml': `${siteConfig.url}/feed.xml`,
      },
    },
    openGraph: {
      type: "website",
      locale: typedLocale === "ar" ? "ar_EG" : "en_US",
      alternateLocale: getAlternateLocales(typedLocale),
      url: getCanonicalUrl("", typedLocale),
      siteName: t("siteName"),
      title: t("siteName"),
      description: t("siteDescription"),
      // OG images are auto-generated by opengraph-image.tsx at 1200x630
      // Fallback static image for crawlers that don't support dynamic images
      images: [
        {
          url: `${siteConfig.url}/assets/og-default.png`,
          width: 1200,
          height: 630,
          alt: `${t("siteName")} - ${typedLocale === "ar" ? "منصة إدارة العمليات التجارية" : "Business Operations & Commerce Platform"}`,
          type: "image/png",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: t("siteName"),
      description: t("siteDescription"),
      // Twitter images are auto-generated by twitter-image.tsx at 1200x600
      images: [
        {
          url: `${siteConfig.url}/assets/og-default.png`,
          width: 1200,
          height: 630,
          alt: `${t("siteName")} - ${typedLocale === "ar" ? "منصة إدارة العمليات التجارية" : "Business Operations & Commerce Platform"}`,
        },
      ],
      creator: siteConfig.social.twitter,
      site: siteConfig.social.twitter,
    },
    icons: {
      icon: [
        { url: "/assets/favicon.ico", sizes: "48x48", type: "image/x-icon" },
        { url: "/assets/favicon.svg", type: "image/svg+xml" },
        { url: "/assets/favicon-96x96.png", sizes: "96x96", type: "image/png" },
      ],
      shortcut: "/assets/favicon.ico",
      apple: [
        {
          url: "/assets/apple-touch-icon.png",
          sizes: "180x180",
          type: "image/png",
        },
      ],
      other: [
        {
          rel: "icon",
          url: "/assets/web-app-manifest-192x192.png",
          sizes: "192x192",
          type: "image/png",
        },
        {
          rel: "icon",
          url: "/assets/web-app-manifest-512x512.png",
          sizes: "512x512",
          type: "image/png",
        },
        {
          rel: "mask-icon",
          url: "/assets/favicon.svg",
          color: "#34d399",
        },
      ],
    },
    other: {
      "msapplication-TileColor": "#1a1f2e",
      "msapplication-config": "/browserconfig.xml",
    },
  };
}

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#1a1f2e" },
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
  ],
  colorScheme: "dark light",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  viewportFit: "cover",
};

interface LocaleLayoutProps {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function LocaleLayout({
  children,
  params,
}: LocaleLayoutProps) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  // Get messages for client components
  const messages = await getMessages();

  const { direction } = localeMetadata[locale as Locale];
  const isRTL = direction === "rtl";

  return (
    <html
      lang={locale}
      dir={direction}
      suppressHydrationWarning
      className={`dark ${inter.variable} ${ibmPlexArabic.variable}`}
    >
      <head>
        {/* Preconnect to critical third-party origins */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        
        {/* DNS prefetch for non-critical resources */}
        <link rel="dns-prefetch" href="https://www.google-analytics.com" />
        <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
        
        {/* Format detection - disable auto-formatting of phone numbers on iOS */}
        <meta name="format-detection" content="telephone=no" />
        
        {/* Mobile app capable */}
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        
        {/* Theme script - must run before body renders */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var c=document.cookie.match(/(?:^|;\\s*)cv_theme=([^;]*)/);var t=c?decodeURIComponent(c[1]):localStorage.getItem('theme');if(t==='light'){document.documentElement.classList.remove('dark')}}catch(e){/* Keep default dark */}})();`,
          }}
        />
      </head>
      <body
        className={`min-h-screen flex flex-col bg-background text-foreground antialiased ${
          isRTL ? "font-arabic" : "font-sans"
        }`}
        suppressHydrationWarning
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header locale={locale as Locale} />
          <main className="flex-1">{children}</main>
          <Footer locale={locale as Locale} />
        </NextIntlClientProvider>
        <AnalyticsProvider />
      </body>
    </html>
  );
}
